version: "3.8"

services:
  db:
    image: postgres:14.2-alpine
    container_name: "comments-rest-api-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - comments-rest-api
    volumes:
      - database_postgres:/var/lib/postgres/data

  api:
    build: .
    container_name: "comments-rest-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_host: "db"
      DB_TABLE: "postgres"
      DB_POST: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - comments-rest-api

volumes:
  database_postgres:

networks:
  comments-rest-api:
    driver: bridge

